name: Next.js Landing Page CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-Install-Dependencies:
    uses: ./.github/workflows/setup.yaml


  build: 
    needs: setup-Install-Dependencies
    uses: ./.github/workflows/build.yaml


  test: 
    needs: build  
    uses: ./.github/workflows/test.yaml

  upload-artifact-to-JFrog: 
    needs: test  
    uses: ./.github/workflows/upload-artifact.yaml
    secrets:
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      JF_URL: ${{ secrets.JF_URL }}