name: Next.js Landing Page CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Next.js and node modules
        id: cache-next-and-npm
        uses: actions/cache@v3
        with:
          path: |
            .next/cache 
            node_modules
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-next- 

  build: 
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore Next.js and node modules cache
        id: restore-next-and-npm-cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache 
            node_modules
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-next- 
      - name: Setup Node.js 
        uses: actions/setup-node@v3 
        with:
          node-version: 18
      - name: Build Next.js Project
        run: npm run build

      - name: Archive artifacts
        run: tar -czf nextjs-build.tar.gz .next
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: nextjs-build.tar.gz

  test: 
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore Next.js and node modules cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache 
            node_modules
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-next-
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run tests
        run: npm test

  downloaf-artifact: 
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        uses: actions/download-artifact@v4
        with:
         name: nextjs-build
      - name: Display structure of downloaded files
        run: ls -R

