name: Next.js Landing page CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
        
      - name: Cache Node.js package manager
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Cache Next.js build cache
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-next-

      - name: Archive artifacts
        run: tar -czf build.tar.gz .next

      - name: Jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI
        run: jfrog rt config --url=${{ secrets.JFROG_URL }} --user=${{ secrets.JFROG_USER }} --apikey=${{ secrets.JFROG_API_KEY }} --interactive=false

      - name: Upload to JFrog Artifactory
        run: jfrog rt u "build.tar.gz" "next-landing-page-generic-local/builds/"
        env:
          JFROG_CLI_ENV_EXCLUDE: "*password*;*secret*;*key*;*token*;*auth*;JF_ARTIFACTORY_*;JF_ENV_*;JF_URL;JF_USER;JF_PASSWORD;JF_ACCESS_TOKEN"
          JFROG_CLI_OFFER_CONFIG: false
          JFROG_CLI_BUILD_NAME: Next.js Landing page CI Pipeline
          JFROG_CLI_BUILD_NUMBER: 5
          JFROG_CLI_BUILD_URL: https://github.com/kyawzawaungdevops/next.js-ci-pipeline/actions/runs/9887326816
          JFROG_CLI_USER_AGENT: setup-jfrog-cli-github-action/4.1.3
          JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR: /home/runner/work/_temp
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
