name: Next.js Landing page CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-node.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
      - name: Cache Node.js package manager
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js from cache
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js from cache
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Build project
        run: npm run build
      - name: Cache Next.js app cache
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-next-
      - name: Archive artifacts
        run: tar -czf nextjs-build.tar.gz .next

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_API_KEY }}
      - name: Push Build to Jfrog Artifactory
        run: |
          export BUILD_NAME="next.js-build"
          export BUILD_MODULE="next.js-module"
          export BUILD_NUMBER="1"
          export PATH_TO_DIRECTORY="/"
          jf rt upload "nextjs-build.tar.gz" next-landing-page-generic-local/ --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
