name: Next.js Landing Page CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-Install-Dependencies:
    uses: ./.github/workflows/setup.yaml
    with:
       node-version: '20'

  build: 
    needs: setup-Install-Dependencies
    uses: ./.github/workflows/build.yaml
    with:
       node-version: '20'

  test: 
    needs: build  
    uses: ./.github/workflows/test.yaml
    with:
       node-version: '20'

  upload-artifact-to-JFrog: 
    needs: test  
    uses: ./.github/workflows/upload-artifact.yaml
    with:
       BUILD_NAME: 'testing'
       BUILD_MODULE: 'test'
       BUILD_NUMBER: '1'     
    secrets:
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      JF_URL: ${{ secrets.JF_URL }}