name: setup Workflow

# trigger
on:
      workflow_call:

jobs:
  setup-node-dependencies:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Next.js and node modules
        id: cache-next-and-npm
        uses: actions/cache@v3
        with:
          path: |
            .next/cache 
            node_modules
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-next- 

 