name: test Workflow

# trigger
on:
      workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore Next.js and node modules cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache 
            node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-cache-
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run tests
        run: npm test

 