name: upload artifact

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      JFROG_API_KEY:
        required: true
    vars:
      JFROG_URL:
        required: true

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
      - name: Jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_ACCESS_TOK
