name: upload artifact

on:
  workflow_call:
    inputs:
          BUILD_NAME:
            required: true
            type: string
          BUILD_MODULE:
            required: true
            type: string
          BUILD_NUMBER:
            required: true
            type: string
    secrets:
      JFROG_API_KEY:
        required: true
      JF_URL:
        required: true

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
      - name: Jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_API_KEY }}
      - name: Push Build to Jfrog-Artifactory
        run: |
          export BUILD_NAME="${{ inputs.BUILD_NAME }}"
          export BUILD_MODULE="${{ inputs.BUILD_MODULE }}"
          export BUILD_NUMBER="${{ inputs.BUILD_NUMBER }}"
          jf rt upload "nextjs-build.tar.gz" next-landing-page-generic-local/ --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
